routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});






/* partie medecin routes*/
Route::group([ 'prefix'=>'medecin' , 'namespace' => 'Medecin' , 'middleware' => ['auth']], function() {
   
     Route::resource('medecin', 'ReclamationController');
     Route::resource('pmedecin', 'PmedecinController');
     Route::resource('amedecin', 'AppointementController');
     
     
   
    
     
     
 });

 /*partie front*/
Route::get('/medecin', 'MedecinController@index')->name('medecin.indexx');
Route::get('/medecin/{id}', 'MedecinController@showw')->name('medecins.showw');


Route::resource('etats','EtatController');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');

Route::resource('typess','typeController');


Route::get('posts/{id}', 'HomeController@show')->name('posts.show');

Route::resource('reclamation','ReclamationController');
//Route::get('/dataa', 'ReclamationController@index');
//Route::post('/storee', 'ReclamationController@store')->name('dataa.store');;

Route::resource('repondres','RepondreController');

Route::resource('informations','InformationController');
Route::resource('premiers','PremierController');
Route::resource('forums','ForumController');

Route::resource('topics','TopicController');
//sujet
Route::post('/comments/{topic}', 'CommentController@store')->name('comments.store');
Route::post('/commentReply/{comment}', 'CommentController@storeCommentReply')->name('comments.storeReply');


//admin
Route::group([ 'prefix'=>'admin' , 'namespace' => 'Admin' , 'middleware' => ['auth']], function() {
   // Route::resource('medicaments', 'MedicamentController');
    Route::resource('specialites', 'SpecialiteController');
    Route::resource('medecins', 'MedecinController');
});


//collecte
Route::get('/collecte1', 'CollecteController@createStep1')->name('signup');
Route::post('/collecte1', 'CollecteController@PostcreateStep1');
Route::get('/collecte2', 'CollecteController@createStep2');
Route::post('/collecte2', 'CollecteController@PostcreateStep2');
Route::get('/collecte3', 'CollecteController@createStep3');
Route::post('/collecte3', 'CollecteController@PostcreateStep3');
Route::post('/remove-image', 'CollecteController@removeImage');
Route::post('/store', 'CollecteController@store');
Route::get('/show', 'CollecteController@show');
Route::get('/data', 'CollecteController@index');
Route::resource('collectes','CollecteController');

Route::resource('collectedons','CollectedonController');
Route::resource('dons','DonController');


/*route d'achat de medicament*/

Route::get('/boutique','ProductController@index')->name('products.index');
Route::get('/boutique/{slug}','ProductController@show')->name('products.show');
Route::get('/search', 'ProductController@search')->name('products.search');

/*panier Routes */
Route::group(['middleware'=>['auth']],function(){
Route::get('/panier', 'CartController@index')->name('cart.index');
Route::post('/panier/ajouter', 'CartController@store')->name('carte.store');
Route::patch('/panier/{rowId}', 'CartController@update')->name('cart.update');
Route::delete('/panier/{rowId}','CartController@destroy')->name('cart.destroy');
});
/*rout de paiement*/
Route::group(['middleware'=>['auth']],function(){
Route::get('/paiement', 'checkoutController@index')->name('checkout.index');
Route::post('/paiement', 'checkoutController@store')->name('checkout.store');
Route::get('/merci', 'checkoutController@thankYou')->name ('checkout.thankYou');
});
/*admin */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin','middleware'=> ['auth']], function () {
    Route::resource('product', 'ProductController'); 
 
     
 });

 //*calendar*//
Route::get('/calendar', function () {
    return view('calendar');
});
Route::resource('/temps','TempsController');
/*rendez_vous*/
Route::resource('rdv','RdvController');

/*types de cancer*/
 Route::resource('chiffre','TypesdecancerController');
 Route::get('/type','TypesController@index')->name('types.index');
 Route::get('/sein','TypesController@index1')->name('types.index1');
 Route::get('/prostat','TypesController@index2')->name('types.index2');
 Route::get('/colon','TypesController@index3')->name('types.index3');
 Route::get('/thyroid','TypesController@index4')->name('types.index4');
 Route::get('/uterus','TypesController@index5')->name('types.index5');
 Route::get('/bouche','TypesController@index6')->name('types.index6');
 Route::get('/rein','TypesController@index7')->name('types.index7');
 Route::get('/foi','TypesController@index8')->name('types.index8');
 Route::get('/cerveau','TypesController@index9')->name('types.index9');
 Route::get('/testiculs','TypesController@index10')->name('types.index10');
 Route::get('/pancreas','TypesController@index11')->name('types.index11');
 Route::get('/os','TypesController@index12')->name('types.index12');
 Route::get('/peau','TypesController@index13')->name('types.index13');
 Route::get('/leucemies','TypesController@index14')->name('types.index14');
 /*conseil*/
 Route::resource('conseil','ConseilController');
 Route::get('/prevention','ConseilController@prevention')->name('conseils.prevention');
 Route::get('/brochure','ConseilController@brochure')->name('conseils.brochure');
 Route::get('/entreprise','ConseilController@entreprise')->name('conseils.entreprise');
 Route::get('/kiabi','ConseilController@kiabi')->name('conseils.kiabi');
 Route::get('/orange','ConseilController@orange')->name('conseils.orange');
 Route::get('/PSA','ConseilController@PSA')->name('conseils.PSA');
 Route::get('/benevol','ConseilController@benevol')->name('conseils.benevol');

/*admin */
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function() {
   
 Route::resource('users','UsersController');
     
 });

resources/views/calendar.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-10 mx-auto my-4">
            <div id='calendar'></div>  
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');//your dive id of calendar
            var calendar = new FullCalendar.Calendar(calendarEl, {
                plugins: [ 'interaction', 'dayGrid' ],
                header: {
                    left: 'prevYear,prev,next,nextYear today',
                    center: 'title',
                    right: 'dayGridMonth,dayGridWeek,dayGridDay'
                },
                defaultDate: '{{ date('Y-m-d') }}',
                navLinks: true, // can click day/week names to navigate views
                editable: true,
                selectable: true,
                select : function(selectionInfo){ //trigger select event
                    let title = prompt("Entrer le titre de la rendez-vous : ");
                    let formatted_start_date = selectionInfo.start.getFullYear() + "-" + (selectionInfo.start.getMonth() + 1) + "-" + selectionInfo.start.getDate() + " " + selectionInfo.start.getHours() + ":" + selectionInfo.start.getMinutes() + ":" + selectionInfo.start.getSeconds(); 
                    let formatted_end_date = selectionInfo.end.getFullYear() + "-" + (selectionInfo.end.getMonth() + 1) + "-" + selectionInfo.end.getDate() + " " + selectionInfo.end.getHours() + ":" + selectionInfo.end.getMinutes() + ":" + selectionInfo.end.getSeconds();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type:'POST',
                        url : "/events",
                        data:{
                            title:title, 
                            start:formatted_start_date, 
                            end:formatted_end_date
                        },
                        success:function(){
                            Swal.fire({
                                position: 'center',
                                icon: 'success',
                                title: 'temps de tarvail ajouté',
                                showConfirmButton: false,
                                timer: 50000000
                            });
                            location.reload();
                        }
                    });
                },
                eventLimit: true, // allow "more" link when too many events
                events :  '/events',
                eventClick: function(info) {// trigger click event
                    const swalWithBootstrapButtons = Swal.mixin({
                        customClass: {
                            confirmButton: 'btn btn-info mx-2',
                            cancelButton: 'btn btn-danger'
                        },
                        buttonsStyling: false
                    })
                    swalWithBootstrapButtons.fire({
                            title: 'Veuillez choisir une action',
                            icon: 'info',
                            showCancelButton: true,
                            cancelButtonText: 'Supprimer',
                            confirmButtonText: 'Voir',
                            reverseButtons: false
                        }).then((result) => {
                        if (result.value) {
                            let link = `http://laravel-tp1.test/events/${info.event.title}`;
                            window.location.href = link;
                        }else{
                            $.ajaxSetup({
                                headers: {
                                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                                }
                            });
                            $.ajax({
                                type:'DELETE',
                                url : "/events/" + info.event.title,
                                success:function(){
                                    Swal.fire({
                                        position: 'center',
                                        icon: 'success',
                                        title: 'date de travail supprimé',
                                        showConfirmButton: false,
                                        timer: 1500
                                    })
                                    location.reload();
                                }
                            });
                        }
                    })
                },
                eventDrop: function(info) { //trigger drop event
                    let formatted_start_date = info.event.start.getFullYear() + "-" + (info.event.start.getMonth() + 1) + "-" + info.event.start.getDate() + " " + info.event.start.getHours() + ":" + info.event.start.getMinutes() + ":" + info.event.start.getSeconds(); 
                    let formatted_end_date = info.event.end.getFullYear() + "-" + (info.event.end.getMonth() + 1) + "-" + info.event.end.getDate() + " " + info.event.end.getHours() + ":" + info.event.end.getMinutes() + ":" + info.event.end.getSeconds();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type:'PUT',
                        url : "/events/" + info.event.title,
                        data:{
                            title:info.event.title, 
                            start:formatted_start_date, 
                            end:formatted_end_date
                        },
                        success:function(){
                            Swal.fire({
                                position: 'center',
                                icon: 'success',
                                title: 'travail modifié',
                                showConfirmButton: false,
                                timer: 1500
                            })
                        }
                    });
                },
                eventResize : function(eventResizeInfo){//trigger event resize
                    let formatted_start_date = eventResizeInfo.event.start.getFullYear() + "-" + (eventResizeInfo.event.start.getMonth() + 1) + "-" + eventResizeInfo.event.start.getDate() + " " + eventResizeInfo.event.start.getHours() + ":" + eventResizeInfo.event.start.getMinutes() + ":" + eventResizeInfo.event.start.getSeconds(); 
                    let formatted_end_date = eventResizeInfo.event.end.getFullYear() + "-" + (eventResizeInfo.event.end.getMonth() + 1) + "-" + eventResizeInfo.event.end.getDate() + " " + eventResizeInfo.event.end.getHours() + ":" + eventResizeInfo.event.end.getMinutes() + ":" + eventResizeInfo.event.end.getSeconds();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type:'PUT',
                        url : "/events/" + eventResizeInfo.event.title,
                        data:{
                            title:eventResizeInfo.event.title, 
                            start:formatted_start_date, 
                            end:formatted_end_date
                        },
                        success:function(){
                            Swal.fire({
                                position: 'center',
                                icon: 'success',
                                title: 'temp de travail modifié',
                                showConfirmButton: false,
                                timer: 1500
                            })
                        }
                    });
                }
            });
            calendar.setOption('locale', 'fr');           
            calendar.render();
            document.querySelector('.fc-dayGridMonth-button').innerHTML = "Mois";
            document.querySelector('.fc-dayGridWeek-button').innerHTML = "Semaine";
            document.querySelector('.fc-dayGridDay-button').innerHTML = "Jour";
            document.querySelector('.fc-today-button').innerHTML = "Ajourd'hui";
        });
    </script>
@endsection

resources/views/create.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-8 mx-auto my-4">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h5 class="card-title p-0 m-0">Ajouter un temps de travail</h5>
                </div>
                <div class="card-body">
                    <form action="{{route('events.store')}}" method="post">
                        @csrf
                        <div class="container">
                            <form>
                                <fieldset class="form-group row">
                                    <legend class="col-form-legend col-sm-1-12">Titre</legend>
                                    <div class="col-sm-1-12">
                                        <input type="text" class="form-control" name="title" id="title" placeholder="Titre*">
                                    </div>
                                </fieldset>
                                <fieldset class="form-group row">
                                    <legend class="col-form-legend col-sm-1-12">Date Début</legend>
                                    <div class="col-sm-1-12">
                                        <input type="date" class="form-control" name="start_date" id="start_date" placeholder="Date Début*">
                                    </div>
                                </fieldset>
                                <fieldset class="form-group row">
                                    <legend class="col-form-legend col-sm-1-12">Date Fin</legend>
                                    <div class="col-sm-1-12">
                                        <input type="date" class="form-control" name="end_date" id="end_date" placeholder="Date Fin*">
                                    </div>
                                </fieldset>
                                <div class="form-group row">
                                    <div class="col-sm-12">
                                        <button type="submit" class="btn btn-primary">Valider</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.master6')

@section('content')
<div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('master5.name', 'Solution Cancer') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                

                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a href="{{ route('topics.create') }}" class="dropdown-item">creér un forum</a>
                                    
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                    @can('manage-users')
                                    <a class="dropdown-item" href="{{ route('admin.users.index') }}">Liste des utilisateurs</a>
                                    @endcan
                                   
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>



















        <section class="hero-wrap js-fullheight" style="background-image: url('images/z1.jpg');" data-stellar-background-ratio="0.5">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tableau de bord</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Vous êtes connecté! 
                    <img src="https://cdn3.iconfinder.com/data/icons/lightly-icons/30/happy-480.png"  height="27" alt="..."> 
                </div>
            </div>
        </div>
    </div>
</div>
</section>
@endsection

resources/views/show.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-8 mx-auto my-4">
            <div class="card">
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <span class="text-primary font-weight-bold">Titre : {{$event->title}}</span>
                        </li>
                        <li class="list-group-item">
                            <span class="text-success font-weight-bold">Date début : {{$event->start_date}}</span>
                        </li>
                        <li class="list-group-item">
                            <span class="text-danger font-weight-bold">Date fin : {{$event->end_date}}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection