routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});






/* partie medecin routes*/
Route::group([ 'prefix'=>'medecin' , 'namespace' => 'Medecin' , 'middleware' => ['auth']], function() {
   
     Route::resource('medecin', 'ReclamationController');
     Route::resource('pmedecin', 'PmedecinController');
     Route::resource('amedecin', 'AppointementController');
     
     
   
    
     
     
 });

 /*partie front*/
Route::get('/medecin', 'MedecinController@index')->name('medecin.indexx');
Route::get('/medecin/{id}', 'MedecinController@showw')->name('medecins.showw');


Route::resource('etats','EtatController');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');

Route::resource('typess','typeController');


Route::get('posts/{id}', 'HomeController@show')->name('posts.show');

Route::resource('reclamation','ReclamationController');
//Route::get('/dataa', 'ReclamationController@index');
//Route::post('/storee', 'ReclamationController@store')->name('dataa.store');;

Route::resource('repondres','RepondreController');

Route::resource('informations','InformationController');
Route::resource('premiers','PremierController');
Route::resource('forums','ForumController');

Route::resource('topics','TopicController');
//sujet
Route::post('/comments/{topic}', 'CommentController@store')->name('comments.store');
Route::post('/commentReply/{comment}', 'CommentController@storeCommentReply')->name('comments.storeReply');


//admin
Route::group([ 'prefix'=>'admin' , 'namespace' => 'Admin' , 'middleware' => ['auth']], function() {
   // Route::resource('medicaments', 'MedicamentController');
    Route::resource('specialites', 'SpecialiteController');
    Route::resource('medecins', 'MedecinController');
});


//collecte
Route::get('/collecte1', 'CollecteController@createStep1')->name('signup');
Route::post('/collecte1', 'CollecteController@PostcreateStep1');
Route::get('/collecte2', 'CollecteController@createStep2');
Route::post('/collecte2', 'CollecteController@PostcreateStep2');
Route::get('/collecte3', 'CollecteController@createStep3');
Route::post('/collecte3', 'CollecteController@PostcreateStep3');
Route::post('/remove-image', 'CollecteController@removeImage');
Route::post('/store', 'CollecteController@store');
Route::get('/show', 'CollecteController@show');
Route::get('/data', 'CollecteController@index');
Route::resource('collectes','CollecteController');

Route::resource('collectedons','CollectedonController');
Route::resource('dons','DonController');


/*route d'achat de medicament*/

Route::get('/boutique','ProductController@index')->name('products.index');
Route::get('/boutique/{slug}','ProductController@show')->name('products.show');
Route::get('/search', 'ProductController@search')->name('products.search');

/*panier Routes */
Route::group(['middleware'=>['auth']],function(){
Route::get('/panier', 'CartController@index')->name('cart.index');
Route::post('/panier/ajouter', 'CartController@store')->name('carte.store');
Route::patch('/panier/{rowId}', 'CartController@update')->name('cart.update');
Route::delete('/panier/{rowId}','CartController@destroy')->name('cart.destroy');
});
/*rout de paiement*/
Route::group(['middleware'=>['auth']],function(){
Route::get('/paiement', 'checkoutController@index')->name('checkout.index');
Route::post('/paiement', 'checkoutController@store')->name('checkout.store');
Route::get('/merci', 'checkoutController@thankYou')->name ('checkout.thankYou');
});
/*admin */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin','middleware'=> ['auth']], function () {
    Route::resource('product', 'ProductController'); 
 
     
 });

 //*calendar*//
Route::get('/calendar', function () {
    return view('calendar');
});
Route::resource('/temps','TempsController');
/*rendez_vous*/
Route::resource('rdv','RdvController');

/*types de cancer*/
 Route::resource('chiffre','TypesdecancerController');
 Route::get('/type','TypesController@index')->name('types.index');
 Route::get('/sein','TypesController@index1')->name('types.index1');
 Route::get('/prostat','TypesController@index2')->name('types.index2');
 Route::get('/colon','TypesController@index3')->name('types.index3');
 Route::get('/thyroid','TypesController@index4')->name('types.index4');
 Route::get('/uterus','TypesController@index5')->name('types.index5');
 Route::get('/bouche','TypesController@index6')->name('types.index6');
 Route::get('/rein','TypesController@index7')->name('types.index7');
 Route::get('/foi','TypesController@index8')->name('types.index8');
 Route::get('/cerveau','TypesController@index9')->name('types.index9');
 Route::get('/testiculs','TypesController@index10')->name('types.index10');
 Route::get('/pancreas','TypesController@index11')->name('types.index11');
 Route::get('/os','TypesController@index12')->name('types.index12');
 Route::get('/peau','TypesController@index13')->name('types.index13');
 Route::get('/leucemies','TypesController@index14')->name('types.index14');
 /*conseil*/
 Route::resource('conseil','ConseilController');
 Route::get('/prevention','ConseilController@prevention')->name('conseils.prevention');
 Route::get('/brochure','ConseilController@brochure')->name('conseils.brochure');
 Route::get('/entreprise','ConseilController@entreprise')->name('conseils.entreprise');
 Route::get('/kiabi','ConseilController@kiabi')->name('conseils.kiabi');
 Route::get('/orange','ConseilController@orange')->name('conseils.orange');
 Route::get('/PSA','ConseilController@PSA')->name('conseils.PSA');
 Route::get('/benevol','ConseilController@benevol')->name('conseils.benevol');

/*admin */
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function() {
   
 Route::resource('users','UsersController');
     
 });

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model

{
    protected $guarded = [];
    public function user()

    {
        return $this->belongsTo('App\User');
    }


public function comments()
{
    return $this->morphMany('App\Comment', 'commentable')->latest();
}
}

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\Topic;
use Illuminate\Http\Request;

class TopicController extends Controller

{
    
    // ne pas le droit de faire supp et edite et ajoute un comtr sans connecté 
        
     //affiche sauf method index, show avec except
      public function __construct()
      {
         
        $this->middleware('auth')->except(['index','show']);
      }

      /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function index()
    //latest : recupere dans un ordre decroissante ,  paginate affiche par page , stoke dans le variable topics
    {
        $topics = Topic::latest()->paginate(5);
        return view('topics.index', compact('topics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //mettre dans la dossier topics est fichier create.blade.php 
        return view('topics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     // recupper les donne dans "data" , recupper le utilisateur connecte avec auth->user->create
    public function store(Request $request)
    {
        
        $data = $request->validate([
            'title' => 'required|min:5',
            'content'=> 'required|min:10'
        ]);

       $topic = auth()->user()->topics()->create($data);

        return redirect()->route('topics.show', $topic->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function show(Topic $topic)
    {
       return view('topics.show', compact('topic'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function edit(Topic $topic)
    {
        $this->authorize('update', $topic);

        return view('topics.edit',compact('topic'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Topic $topic)
    {
        $this->authorize('update', $topic);
        $data = $request->validate([
            'title' => 'required|min:5',
            'content'=> 'required|min:10'
        ]);
        //  en pass le methode update avec les donnee data 
        $topic->update($data);

        return redirect()->route('topics.show',$topic->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
        $this->authorize('delete', $topic);
        Topic::destroy($topic->id);
        return redirect('/topics');
    }
}

resources/views/topics/create.blade.php
@extends('layouts.master3')

@section('extra-js')
{!! NoCaptcha::renderJs() !!}


@section('content')
 <div class="container">
 <br><br><br>
   <h1>Creér un Sujet</h1>
   <hr>
   <form action="{{  route('topics.store') }}" method="post">
   <!-- pour protege le file web -->
   @csrf
   <div class="form-group">
   
    <label for="title">Titre de Sujet</label>
    <input type="text" class="form-control @error('title') is-invalid @enderror"  name="title" id="title">
    <!-- si ilya une error affiche error -->
    @error('title')
    <div class="invalid-feedback">{{ $errors->first('title') }}</div>
    @enderror
    </div>
   <div class="form-group">
   <label for="content">votre sujet</label>
   <textarea name="content" id="content" class="form-control @error('content') is-invalid @enderror" rows="5"></textarea>
   
   @error('content')
    <div class="invalid-feedback">{{ $errors->first('content') }}</div>
    @enderror

   </div>
   
   <button type="submit" class="btn btn-primary">Creér mon Sujet</button>
   </form>
 </div>
@endsection

resources/views/topics/edit.blade.php
@extends('layouts.app')


@section('content')
 <div class="container">
 <section class="hero-wrap js-fullheight" style="background-image: url('images/z1.jpg');" data-stellar-background-ratio="0.5">
   <h1>{{ $topic->title}}</h1>
   <hr>
   <!-- envoie topics.update et retour $topic -->
   <form action="{{ route('topics.update', $topic) }}" method="post">
   <!-- pour protege le file web -->
   @csrf
   @method('PATCH')
   <div class="form-group">
   
    <label for="title">Titre du Topic</label>
    <input type="text" class="form-control @error('title') is-invalid @enderror" 
     name="title" id="title" value="{{ $topic->title }}">
    <!-- si ilya une error affiche error -->
    @error('title')
    <div class="invalid-feedback">{{ $errors->first('title') }}</div>
    @enderror
    </div>
   <div class="form-group">
   <label for="content">votre sujet</label>
   <textarea name="content" id="content" class="form-control @error('content') is-invalid @enderror"
    rows="5">{{ $topic->content }}</textarea>
   @error('content')
    <div class="invalid-feedback">{{ $errors->first('content') }}</div>
    @enderror

   </div>
   <button type="submit" class="btn btn-primary">modifier mon topic</button>
   </form>
 </div>
 </section>
@endsection

resources/views/topics/index.blade.php
@extends('layouts.app')


@section('content')
<section class="hero-wrap js-fullheight" style="background-image: url('images/z1.jpg');" data-stellar-background-ratio="0.5">
 <div class="container">
 <button type="button" class="btn btn-outline-primary "><a href="{{ route('topics.create') }}" class="dropdown-item">creér un forum</a></button>
 
   <div class="list-group">
<!-- list--group-item ou bien card  , mettre h4 en tant que lien , mettre l'heure et nom de louteur -->
     @foreach ($topics as $topic)
      <div class="card">
        <h4><a href="{{ route('topics.show' , $topic) }}">{{ $topic->title }}</a></h4>
        <p>{{ $topic->content }}</p>
        <div class="d-flex justify-content-between align-items-center">
         <Medium>Posté le {{ $topic->created_at->format('d/m/Y a H:m') }}</Medium>
         <span class="badge badge-primary"><h6>{{ $topic->user->name }}</h6></span>
        </div>
      </div>

     @endforeach
   
   </div>
   <!-- pour le nombre de page  , mt= marge top 3 -->
   <div class="d-flex justify-content-center mt-3"> {{ $topics->links() }} </div> 
 </div>
 </section>
@endsection

resources/views/topics/show.blade.php
@extends('layouts.app')

@section('extra-js')
<script>
  function toggleReplyComment(id)
  {
     let element = document.getElementById('replyComment-' + id);
      element.classList.toggle('d-none');
  }
</script>
@endsection

@section('content')
<section class="hero-wrap js-fullheight" style="background-image: url('images/z1.jpg');" data-stellar-background-ratio="0.5">
<div class="container">
<br><br><br>
 <div class="card">
  <div class="card-body">
   <h5 class="card-title">{{ $topic->title}}</h5>
    <p>{{ $topic->content }}</p>
    <div class="d-flex justify-content-between align-items-center">
         <Medium>Posté le {{ $topic->created_at->format('d/m/Y a H:m') }}</Medium>
         <span class="badge badge-primary"><h6>{{ $topic->user->name }}</h6></span>
    </div>
    <div class="d-flex justify-content-between align-items-center mt-3">
    <!-- can pour protege le formation de l'autheur update et delete -->
    @can('update', $topic)
     <a href="{{ route('topics.edit', $topic) }}" class="btn btn-warning">editer topic</a>
     @endcan
     @can('delete', $topic)
      <form action="{{ route('topics.destroy', $topic) }}" method="post">
      @csrf 
      @method('DELETE')
      <button type="submit" class="btn btn-danger">Supprimer</button>
      </form>
      @endcan

    </div>
 </div>

</div>

<hr>
<h5>Commentaires</h5>
 @forelse ($topic->comments as $comment)
  <div class="card mb-2">
  <div class="card-body">
  <h2>{{ $comment->content }}</h2> 
   <div class="d-flex justify-content-between align-items-center">
         <Medium>Posté le {{ $comment->created_at->format('d/m/Y') }}</Medium>
         <span class="badge badge-primary"><h6>{{ $comment->user->name }}</h6></span>
        </div>
  </div>
  </div>
   <!-- rep de comtr -->
  @foreach ($comment->comments as $replyComment)
  <div class="card mb-2 ml-5">
  <div class="card-body">
  <h2>{{ $replyComment->content }}</h2> 
   <div class="d-flex justify-content-between align-items-center">
         <Medium>Posté le {{ $replyComment->created_at->format('d/m/Y') }}</Medium>
         <span class="badge badge-primary"><h6>{{ $replyComment->user->name }}</h6></span>
        </div>
  </div>
  </div>
  @endforeach

  @auth
   <button  class="btn btn-info mb-3" onclick="toggleReplyComment({{ $comment->id }})">Répondre</button>
    <form action="{{ route('comments.storeReply', $comment) }}"
     method="post" class="mb-3 ml-5 d-none" id="replyComment-{{ $comment->id }}">
     @csrf
      <div class="form-group">
       <label for="replyComment">Ma réponce</label>
        <textarea name="replyComment"  class="form-control @error('replyComment') 
        is-invalid @enderror" id="replyComment" rows="5"></textarea>
        @error('replyComment')
        <div class="invalid-feedback">{{ $errors->first('replyComment') }}</div>
        @enderror

      </div>
      <button type="submit" class="btn btn-primary">Repondre a ce commentaire</button>
    </form>
    @endauth
  @empty
   <div class="alert alert-info">Aucun commentaire pour ce topic</div>
   @endforelse
 <form action="{{ route('comments.store', $topic) }}" method="post" class="mt-3">
  @csrf 

   <div class="form-group">
     <label for="content">Votre commentaire</label>
     <textarea class="form-control @error('content') is-invalid @enderror" name="content" id="content" rows="5">
     </textarea>
     
     @error('content')
   <div class="invalid-feedback">{{ $errors->first('content') }}</div>
   @enderror
   </div>
  
    
    <button type="submit" class="btn btn-primary">Soumettre mon commentaire</button><br><hr>
    <button type="submit" class="btn btn-dark"><a href="{{route('topics.index')}}">retourne au sujet</a></button>
 </form>
</div>
</section>
@endsection